# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3bc61d4a9392dfd9e6c1d86be1c49ce8e4a645a6b2d9c45f1175567ab2f2db4b6d70360bbd259d1f0d6ddc6c1bd88acf24bace12ba133a14d02fc31d79c0ffe

test:
  secret_key_base: 2c6a0d9b4dc909df4c697e66360eb952e0ec89bdd888b6e3fef9c96822d9bbf99b6678fc36791c0c2e851493eb23996d43c836c24073b15f7f1f0c3ef7e405d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
